name: example-environment
channels:
    - conda-forge
dependencies:
    - python    # Python version 3.6
    - xarray    # N-d labeled array library
    - numpy         # N-d array and numerics
    - scipy         # Common math/stats/science functions
    - matplotlib    # 2D plotting library
    - cartopy       # Geographic plotting toolkit
    - pandas        # Labeled array library
    - netcdf4       # Wrapper for netcdf4
    - geopandas
    - pyferret
    - ferret_datasets
    - seaborn       # Statistical visualizations
    - cmocean
    - pip:
      - ferretmagic
